#!/bin/bash

PERF_DATA=$1

#perf script -i $PERF_DATA > perf.unfold

/mnt/datas/dev_tools/flame_graph/stackcollapse-perf.pl $PERF_DATA > perf.folded
/mnt/datas/dev_tools/flame_graph/flamegraph.pl perf.folded > flames.svg
firefox flames.svg
